"====================================================================
"                           ~My vimrc~
"====================================================================
" Author: Chris Jones [http://chrisrjones.com]
" Source: https://github.com/ipatch/dotfiles/blob/master/vim/vimrc
"-------------------------------------------------------------------

" Note when seeing 'imap' below it is referencing when vim is in
" insert mode.

" Note when seeing 'nmap' below it is when the vim editor is in
" normal mode.

" Easy access to the start of the line, the below configuration will
" map the '^' key to the '0' key, and move the cursor to first
" character of a line.
nmap 0 ^

"Want to set this before any others, the default 'leader' key is \
" set the 'leader' key to ','
let mapleader = ','

" Note - to map the 'leader' key to the spacebar using the following,
" and remove the single quotes around the double quotes of the word Space.
" let mapleader = '"\<Space>"'

" Note - the below two configuration commands are for editing the vimrc file.
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

" Edit .vimrc file in a new tab
map <Leader>vi :tabe ~/.vimrc<CR>

"----------------------Auto-Commands------------------------------------------"

" Automatically source the VIMRC file on save.
augroup autosourcing
	autocmd!
	autocmd BufwritePost .vimrc source %
augroup END

" nmap <leader>h :echo "Hello"<cr>

" <C-[>
" capslock to escape

" Note - the below 'insert mappings will bind 'jk' / 'kj' to the ESC
" key functionality, so the ESC key does not need to be pressed when in insert
" mode.
imap jk <esc>
imap kj <esc>

" Set / place line numbers on the left / in the gudder of the editor.
set number

" the below key mapping will indent the entire file
map <Leader>i mmgg=G`m<CR>

" =============================================================================
" Vundle - below are configurations to make the Vundle plugin manager happy :)
" =============================================================================

"Don't maintain compatibility with Vi. - VUNDLE HAPPINESS :)
set nocompatible

"Remember last 1000 commands
set history=1000

" the below line is required in order to get vundle to work - VUNDLE HAPPINESS
filetype off "required

" set the runtime path to include Vundle and initialize - VUNDLE HAPPINESS
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required - VUNDLE HAPPINESS
Plugin 'VundleVim/Vundle.vim'

" BELOW - are the added VIM plugins using Vundle to manage them.  The string
" after the word 'Plugin' is a GH username followed by a repo name.  Vundle is
" aware of GH username/repo out of the box. :)

" add Vim plugin for rails support
Plugin 'tpope/vim-rails'
Plugin 'ctrlpvim/ctrlp.vim' " CtrlP is a fuzzy finder.
Plugin 'thoughtbot/vim-rspec'
Plugin 'vim-airline/vim-airline'
Plugin 'sickill/vim-monokai'
Plugin 'flazz/vim-colorschemes'

" the below two (2) lines are required for the above color scheme
" the below configuration option will turn on syntax highlighting
" for editing code files such as .rb .php etc etc.
syntax enable

" To enable 256 colors in vim, put this your .vimrc before setting the
" colorscheme: 
set t_Co=256

"colorscheme monokai
colorscheme molokai 

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" " To ignore plugin indent changes, instead use:
" "filetype plugin on
" "
" " Brief help
" " :PluginList       - lists configured plugins
" " :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line

" highlight cursor line
set cursorline

" move cursor with mouse
" Note - if running vim within Terminal.app < 10.11 two additional pieces of
" software will need to be installed for registering mouse events.
" SEE - http://www.culater.net/software/SIMBL/SIMBL.php
" SEE - https://bitheap.org/mouseterm/
set mouse=a

" enable the <delete> key on a mbp to act as backspace
set backspace=indent,eol,start
