"====================================================================
"                           ~My vimrc~
"
"====================================================================
"
" Author: Chris Jones [http://chrisrjones.com]
" Source: https://github.com/ipatch/dotfiles/blob/master/vim/vimrc
"
" -------------------------------------------------------------------

"Easy access to the start of the line
nmap 0 ^

"Want to set this before any others
let mapleader = "\<Space>"

nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>

"Edit .vimrc file in a new tab
map <Leader>vi :tabe ~/.vimrc<CR>

" nmap <leader>h :echo "Hello"<cr>

" <C-[>
" capslock to escape
imap jk <esc>
imap kj <esc>

set number

" the below key mapping will indent the entire file
map <Leader>i mmgg=G`m<CR>

"Don't maintain compatibility with Vi.
set nocompatible

"Remember last 1000 commands
set history=1000

" the below line is required in order to get vundle to work
filetype off "required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" add Vim plugin for rails support
Plugin 'tpope/vim-rails'
Plugin 'ctrlpvim/ctrlp.vim' " CtrlP is a fuzzy finder.
Plugin 'thoughtbot/vim-rspec'
Plugin 'vim-airline/vim-airline'
Plugin 'sickill/vim-monokai'
Plugin 'flazz/vim-colorschemes'

" the below two (2) lines are required for the above color scheme
" the below configuration option will turn on syntax highlighting
" for editing code files such as .rb .php etc etc.
syntax enable
"colorscheme monokai
colorscheme molokai 

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" " To ignore plugin indent changes, instead use:
" "filetype plugin on
" "
" " Brief help
" " :PluginList       - lists configured plugins
" " :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" " :PluginSearch foo - searches for foo; append `!` to refresh local cache
" " :PluginClean      - confirms removal of unused plugins; append `!` to
" auto-approve removal
" "
" " see :h vundle for more details or wiki for FAQ
" " Put your non-Plugin stuff after this line

" highlight cursor line
set cursorline

" move cursor with mouse
set mouse=a
