function shell_color_palette --description 'set some colors 🌈 for the shell'
  # Credit 💳 https://www.reddit.com/r/linux/comments/qagsu/easy_colors_for_shell_scripts_color_library/
  # Credit 💳 https://www.youtube.com/watch?v N8pdAvIwj28
  # Refrence https://stackoverflow.com/a/2099478/708807

  set bold (echo -en "\e[1m")
  set underline (echo -en "\e[4m")
  set dim (echo -en "\e[2m")
  set strickthrough (echo -en "\e[9m")
  set blink (echo -en "\e[5m")
  set reverse (echo -en "\e[7m")
  set hidden (echo -en "\e[8m")
  set normal (echo -en "\e[0m")
  set black (echo -en "\e[30m")
  set red (echo -en "\e[31m")
  set green (echo -en "\e[32m")
  set orange (echo -en "\e[33m")
  set blue (echo -en "\e[34m")
  set purple (echo -en "\e[35m")
  set aqua (echo -en "\e[36m")
  set gray (echo -en "\e[37m")
  set darkgray (echo -en "\e[90m")
  set lightred (echo -en "\e[91m")
  set lightgreen (echo -en "\e[92m")
  set lightyellow (echo -en "\e[93m")
  set lightblue (echo -en "\e[94m")
  set lightpurple (echo -en "\e[95m")
  set lightaqua (echo -en "\e[96m")
  set white (echo -en "\e[97m")
  set default (echo -en "\e[39m")
  set BLACK (echo -en "\e[40m")
  set RED (echo -en "\e[41m")
  set GREEN (echo -en "\e[42m")
  set ORANGE (echo -en "\e[43m")
  set BLUE (echo -en "\e[44m")
  set PURPLE (echo -en "\e[45m")
  set AQUA (echo -en "\e[46m")
  set GRAY (echo -en "\e[47m")
  set DARKGRAY (echo -en "\e[100m")
  set LIGHTRED (echo -en "\e[101m")
  set LIGHTGREEN (echo -en "\e[102m")
  set LIGHTYELLOW (echo -en "\e[103m")
  set LIGHTBLUE (echo -en "\e[104m")
  set LIGHTPURPLE (echo -en "\e[105m")
  set LIGHTAQUA (echo -en "\e[106m")
  set WHITE (echo -en "\e[107m")
  set DEFAULT (echo -en "\e[49m");
end
