
#. $HOME/.asdf/asdf.sh
#. $HOME/.asdf/completions/asdf.bash

# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
