filetype plugin indent on
syntax on
set background=light
" colorscheme solarized8_light

set number
set laststatus=2
set modelines=5
set vb t_vb=
set ts=2 sts=2 sw=2 expandtab
set listchars=tab:‣\ ,eol:¬
set incsearch
set nojoinspaces
set display+=lastline

if has('nvim')
  let g:loaded_sensible=0

  " Keymappings for Neovim
  " By default to exit out of `terminal` mode in nvim use `<C-\><C-n>`
  " Instead map `<Esc>`
  tnoremap <Esc> <C-\><C-n>
  tnoremap <A-[> <Esc>
endif

packadd minpac
call minpac#init()

call minpac#add('tpope/vim-surround')
call minpac#add('tpope/vim-unimpaired')
call minpac#add('tpope/vim-scriptease', {'type': 'opt'})
call minpac#add('machakann/vim-highlightedyank')
" Package for pretty colors 🌈 and aesthetics
call minpac#add('chriskempson/base16-vim')
call minpac#add('vim-airline/vim-airline')
call minpac#add('vim-airline/vim-airline-themes')
" Package for displaying git branches in the status bar
call minpac#add('tpope/vim-fugitive')
call minpac#add('Yggdroot/indentLine') " Add vertical indentation lines

" Package for syntax highlighting for various languages
call minpac#add('sheerun/vim-polyglot')
" Package for quickly commenting lines in code files
call minpac#add('tpope/vim-commentary')

"""""
"
" Load `minpac` LAST!
"
call minpac#add('k-takata/minpac', {'type': 'opt'})

command! PackUpdate call minpac#update()
command! PackClean call minpac#clean()
