# User specified file for configuring the BASH.
# Author: Chris Jones
# Contact: @truckmonth chris.r.jones.1983@gmail.com

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

# Add aliases in ~/.bash_profile

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash
