# User specified file for configuring BASH.
# Author: Chris Jones
# Contact: @truckmonth <- twitter
# Contact: chris.r.jones.1983@gmail.com <- email

# NOTE: in macOS ~/.bashrc is loaded before ~/.bash_profile
# 1) /etc/profile
# 2) /etc/bash.bashrc
# 3) ~/.bashrc
# 4) ~/.bash_profile
# 5) ~/.bash_login
# 6) ~/.profile
# 7) ~/.bash_logout

alias l='ls -lah'
alias cp='cp -iv'
alias rm='rm -iv'
alias mv='mv -iv'

# aliases for git projects
alias gs='git status'
alias gd='git diff --stat'
alias ga='git add --all'
alias gp='git push'

# new aliases - added December 15, 2016
alias df='df -h'
alias du='du -h'

alias dotfiles='cd /opt/Code/dotfiles'

# check to see if $HOME/.bash_profile exists then load in current shell session.
if [ -f ~/.bash_profile ]; then
   source ~/.bash_profile
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin/" # Add linuxbrew to the PATH

# Add aliases in ~/.bash_profile

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Env Vars
export XDG_CONFIG_HOME="$HOME/.config"

# Env Vars for git
export GIT_RC="$XDG_CONFIG_HOME/git"
