# User specified file for configuring the BASH.
# Author: Chris Jones
# Contact: @truckmonth chris.r.jones.1983@gmail.com

# NOTE: in macOS ~/.bashrc is loaded before ~/.bash_profile
# 1) /etc/profile
# 2) /etc/bash.bashrc
# 3) ~/.bashrc
# 4) ~/.bash_profile
# 5) ~/.bash_login
# 6) ~/.profile
# 7) ~/.bash_logout

# check to see if $HOME/.bash_profile exists then load in current shell session.
if [ -f ~/.bash_profile ]; then
   source ~/.bash_profile
fi

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin/" # Add linuxbrew to the PATH

# Add aliases in ~/.bash_profile

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Env Vars
export XDG_CONFIG_HOME="$HOME/.config"

# Env Vars for git
export GIT_RC="$XDG_CONFIG_HOME/git"
